// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            uint64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Url           string
	UserID        string
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        uint64
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	FeedID    int32
}

type Post struct {
	ID          uint64
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt time.Time
	Url         string
	FeedID      int32
}

type User struct {
	ID        string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
