// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :execresult
INSERT INTO
  posts (created_at, updated_at, feed_id, title, url, description, published_at)
VALUES
  (?, ?, ?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FeedID      int32
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
	)
}
